### ISSUE TITLE
import error in jupyter notebook; first code cell

### ISSUE THREAD

**Issue by bnord** [sibirrer/lenstronomy#1]
[IPKernelApp] Exception in execute request:
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-f1d3a41f75c4> in <module>()
      2 
      3 # import main simulation class of lenstronomy
----> 4 from lenstronomy.Extensions.SimulationAPI.simulations import Simulation
      5 
      6 SimAPI = Simulation()

/Users/nord/Projects/lenstronomy/lenstronomy/Extensions/SimulationAPI/simulations.py in <module>()
----> 1 from lenstronomy.ImSim.make_image import MakeImage
      2 from lenstronomy.ImSim.lens_model import LensModel
      3 from lenstronomy.Solver.image_positions import ImagePosition
      4 import astrofunc.util as util
      5 from astrofunc.util import Util_class

/Users/nord/Projects/lenstronomy/lenstronomy/ImSim/make_image.py in <module>()
      3 from lenstronomy.ImSim.lens_model import LensModel
      4 from lenstronomy.ImSim.light_model import LensLightModel, SourceModel
----> 5 from lenstronomy.ImSim.point_source import PointSource
      6 
      7 from lenstronomy.ImSim.data import Data

/Users/nord/Projects/lenstronomy/lenstronomy/ImSim/point_source.py in <module>()
      1 import numpy as np
      2 
----> 3 import astrofunc.util as util
      4 
      5 

ImportError: No module named astrofunc.util

**Comment by sibirrer** [comment]
was there an error message in the installation about astrofunc? This should be a requirement in the installaton process (see requirements.txt). Otherwise try to install (also in development mode) the astrofunc package separately.

**Comment by bnord** [comment]
inside the requirements.txt doc:

mock
-e git://github.com/sibirrer/astrofunc.git#egg=astrofunc

**Comment by bnord** [comment]
git cloned astrofunc 
developer installed.

fastell4py was also missing
git cloned and dev installed that.

**Comment by bnord** [comment]
notebook works start to finish now without error. Have not yet tried changing the options.

Thanks!
