### ISSUE TITLE
redesign input arguments in ray_shooting_partial

### ISSUE THREAD

**Issue by sibirrer** [sibirrer/lenstronomy#102]
@dangilman I will re-design the input statements for 'keep_range' in the ray_shooting_partial function.
Reason: When performing multi-source plane ray-shooting, there are different but reoccurring redshifts (and thus values) of the first and last T_xy statements.
Proposed design changes: make optional arguments for T_start and T_stop defined in the input and leave it to a higher hierarchical class to store whatever values are necessary in their own cache.
Workaround for you: compute and store the T_start/T_stop statements in the class that accesses ray_shooting_partial with keep_range=True.

If this is fine with you, I proceed with the re-design.

**Comment by dangilman** [comment]
Hi,

I don’t actually use those arguments so go ahead

- Daniel

**Comment by sibirrer** [comment]
re-design completed
