### ISSUE TITLE
Print the reason for likelihood punishment to facilitate model inspection

### ISSUE THREAD

**Issue by ajshajib** [sibirrer/lenstronomy#106]
It would be helpful to printout the reason for the punishment in likelihood, if any, when it prints out the *reduced X^2* and the `logL` after each fitting sequence.

**Comment by sibirrer** [comment]
Hi Anowar, the logL value gets read out of the chain and it does not re-compute the likelihood when the printing is performed, so no recovery is possible without re-evaluating the likelihood. As a work-around, I can put a verbose statement in the logL() definition that in post processing can give you the print statements for the various likelihood terms (not only punishments). Does this sound ok?

**Comment by ajshajib** [comment]
That is fine. So, can the `verbose` option be passed when fitting, e.g., through `FittingSequence()`?

**Comment by sibirrer** [comment]
Well, in that case, all likelihood evaluations will get print statements, which I want to avoid. You could e.g.:
1. run one PSO
2. plot the model and diagnostic plots automatically and execute the logL computation with verbose statement
3. run another PSO with the same FittingSequence instance
...
In that way you have full control over what diagnostics you want to see after each step. Does this sound ok?

**Comment by ajshajib** [comment]
Yes, I think that would be sufficient.

**Comment by sibirrer** [comment]
I just pushed an update that allows in the logL() definition to specify a verbose=True statement. Please close the issue if this is sufficient or let me know if not.

**Comment by ajshajib** [comment]
Thanks! Do I have to create a `LikelihoodModule` instance by myself to then call it's `logL()` method, or is there any other top-level class that would readily provide an instance, e.g., `ModelPlot`?

**Comment by sibirrer** [comment]
you have access to the LikelihoodModule through FittingSequence.LikelihoodModule, that is probably the easiest way.

**Comment by ajshajib** [comment]
Great, thanks!
