### ISSUE TITLE
Optimizer functionality is using private functions of other modules

### ISSUE THREAD

**Issue by sibirrer** [sibirrer/lenstronomy#107]
@dangilman I re-designed a bit the multi-plane lensing module for better control of when to compute the observed-to-physical position convention (could improve the speed in the lens equation solver as currently a bottleneck for Anowar).
During the re-design, I was forced to change/update your Optimizer modules as they access private functions of LensModel. Everything should work for you and all the tests pass.

In the longer term: either get rid of the private function calls (by demanding specific features out of the lens model module) or perhaps you can directly more use the updated lens model module as it is improving. Up to you. I just let you know and feel free to close that issue.

**Comment by dangilman** [comment]
Hi,

Yeah makes sense, from now on I won’t write functions that access private
attributes/functions

Daniel

**Comment by sibirrer** [comment]
@dangilman I am closing this issue because you are the sole user for the moment of this module but have added #TODO parts in the code referencing the issue for your next PR :)
