### ISSUE TITLE
removal of ray_shooting_partial_steps?

### ISSUE THREAD

**Issue by sibirrer** [sibirrer/lenstronomy#108]
@dangilman Do you still use the definition ray_shooting_partial_steps or can I remove it from lenstronomy? Just to be sure as I don't see this function being applied in the optimizer. Thanks, Simon

**Comment by dangilman** [comment]
Hi Simon,

I do use it outside of lenstronomy. I can figure out a way around it, but
give me a few weeks

Daniel

**Comment by sibirrer** [comment]
no problem. We can keep it. Let me know if you have issues with the current version.
