### ISSUE TITLE
Return plotted matrix from the outplot methods

### ISSUE THREAD

**Issue by ajshajib** [sibirrer/lenstronomy#112]
It is a convenience feature for the users to make their own customized plotting with the plotted matrix without having to generate the matrix. It would be useful if, e.g., `ModelPlot.source_plot()` returns `ax, source` etc. It may not be necessary to return `ax` at all, as the user already provides the `axes` instance to the method in the first place.

**Comment by sibirrer** [comment]
indeed, ax as return is not required. Generally, I don't like functions without a return statement and this way at least in makes sure the user understands that the ax object got updated. We can discuss tomorrow if there is a better/simpler way to provide it. Thanks

**Comment by sibirrer** [comment]
I pushed a version that includes a routine called source() that should do what you requested.

**Comment by ajshajib** [comment]
Thanks! I will check it out on the next opportunity.
