### ISSUE TITLE
errors in the convergence integrals due to x_grid-x_mean close to 0 (during calculation of the deflection angles from kappa maps)

### ISSUE THREAD

**Issue by LyneVdV** [sibirrer/lenstronomy#114]
In lentronomy 0.8.2 (using python 3.6, scipy 1.10, numpy 1.15.4), I encountered an issue with the convergence integrals (lenstronomy/LensModel/numerical_profile_integrals.py) : sometimes, the (x_grid-x_mean) (line 130 in calcultation of r2 in _deflection_kernel) is close to 0 (around 10**-16) which makes r2 around 10**-32. So kernel_x is exploding and bias the fftconvole (line 101 in deflection_from_kappa). There is an attempt to avoid this kind of error with the line l0 = np.where(r2 == 0) (line 131 in _deflection_kernel). But 10**-32 is not included in this condition. Replacing  " l0 = np.where(r2 == 0)" by "l0 = np.where(util.array2image(r2) < 10**-10)" solves the problem. It would be great to make this small change (or something like that) for the next version if possible. And there might be the same kind of problem with _potential_kernel but I did not encountered it.

**Comment by sibirrer** [comment]
Hi Lyne, I see. The thing of the routine numerics_profile_integrals is a rather 'quick and dirty' integral of  a convergence distribution. When the model is diverging in convergence (as a SIS does in it's center), such a grid integration becomes unstable. I can make it more stable but that does not mean that it is accurate in general (no numerical integrator is generally accurate and finite in speed).

**Comment by sibirrer** [comment]
@LyneVdV  I pushed a more stable integration kernel. Please re-open if this did not fix your issue. Thanks
