### ISSUE TITLE
inv_bool not propagated : is it desired ?

### ISSUE THREAD

**Issue by aymgal** [sibirrer/lenstronomy#116]
Hi Simon, just had a doubt reading this part if the code :

https://github.com/sibirrer/lenstronomy/blob/206871b8f49c8a5af5cfdca6ba3f40e32017ac40/lenstronomy/ImSim/image_linear_solve.py#L54

Is it ok to not propagate to the private method the `inv_bool` that controls the full linear inversion here ?

**Comment by sibirrer** [comment]
Hi Aymeric, no, was not desired. It got introduced a few weeks back I think. The linear prior normalization with shapelet coefficients might be a bit subtle. Anowar and I are working/testing on a separate branch possible ways to deal with this.
