### ISSUE TITLE
4 points solver and joint centroids

### ISSUE THREAD

**Issue by aymgal** [sibirrer/lenstronomy#121]
When joining the center of the first mass profile in the lens model list to some other profile, for a **quad** lens, `center_x` and `center_y` do not take the correct expected value, because there are inferred by the non-linear solver (`'PROFILE'` or `'PROFILE_SHEAR'`) instead.

In this case, the use of no solver (`'NONE'`) would be the solution, but increasing the sampling time. Is there a way to keep using the non-linear solver but forcing the center coordinates to be consistent with such constraints ?

**Comment by sibirrer** [comment]
@aymgal currently, there is no other way to leave them free. I could suggest you two options: 1. for a composite model, the first model is an NFW profile and you can 'at least' link the composite parts with each other.
2. you can give a Gaussian prior on the position of the lens model (whose position is determined separately) that can be used.

I am thinking of having a proper solution without applying a solver (also for testing purpose) but it's not implemented yet.

**Comment by aymgal** [comment]
@sibirrer Alright, thanks for the tips. I close the issue, at least for now.
