### ISSUE TITLE
Issue with PointSource.linear_response_set(...)

### ISSUE THREAD

**Issue by Vedant-Sahu** [sibirrer/lenstronomy#122]
The function PointSource.linear_response_set(....) is providing different outputs for the same input. Sometimes, the function outputs 3 values for x_pos and amp, whereas sometimes it provides 4. The code from the Jupyter Notebook is given below.

import numpy as np
import pickle
from PIL import Image
import matplotlib.pyplot as plt
import matplotlib

%matplotlib inline

import lenstronomy.Util.data_util as data_util
import lenstronomy.Util.util as util
import lenstronomy.Plots.plot_util as plot_util
import lenstronomy.Util.param_util as param_util
from lenstronomy.SimulationAPI.sim_api import SimAPI
from lenstronomy.LensModel.lens_model import LensModel
from lenstronomy.LensModel.Solver.lens_equation_solver import LensEquationSolver

file = open("lens_outputs_new.pickle", "rb")
lens_outputs = pickle.load(file, encoding='latin1')

HST_camera = {'pixel_scale': 0.05, # scale (in arcseonds) of pixels
                  }
    
numpix = 128  # number of pixels per axis of the image to be modelled
 

read_noise = [14, 3, 3]
ccd_gain = [2.5, 1.5, 1.5]
exposure_time = [2196.9, 1429, 1119.2]
sky_brightness = [22.9617, 23.1502, 24.1893]
magnitude_zero_point  = [24.9514, 24.6997, 25.7388]
num_exposures = [1, 1, 1]
seeing = [0, 0, 0]
psf_lens_index = 0

HST_F160W_band_obs = {'read_noise': read_noise[0], # std of noise generated by read-out (in units of electrons)
                           'ccd_gain': ccd_gain[0], # electrons/ADU (analog-to-digital unit). A gain of 8 means that the camera digitizes the CCD signal so that each ADU corresponds to 8 photoelectrons.
                           'exposure_time': exposure_time[0],  # exposure time per image (in seconds)
                           'sky_brightness': sky_brightness[0],  # sky brightness (in magnitude per square arcseconds)
                           'magnitude_zero_point': magnitude_zero_point[0],  # magnitude in which 1 count per second per arcsecond square is registered (in ADU's)
                           'num_exposures': num_exposures[0],  # number of exposures that are combined
                           'seeing': seeing[0],  # full width at half maximum of the PSF (if not specific psf_model is specified)
                           'psf_type': 'PIXEL',  # string, type of PSF ('GAUSSIAN' and 'PIXEL' supported)
                           'psf_model': lens_outputs[psf_lens_index]['multi_band_list'][0][1]['kernel_point_source']  # 2d numpy array, model of PSF centered with odd number of pixels per axis (optional when psf_type='PIXEL' is chosen)
                          }

HST_F814W_band_obs = {'read_noise': read_noise[1],
                           'ccd_gain': ccd_gain[1],
                           'exposure_time': exposure_time[1],
                           'sky_brightness': sky_brightness[1],
                           'magnitude_zero_point': magnitude_zero_point[1],
                           'num_exposures': num_exposures[1],
                           'seeing': seeing[1],
                           'psf_type': 'PIXEL',
                           'psf_model': lens_outputs[psf_lens_index]['multi_band_list'][1][1]['kernel_point_source']
                           }

HST_F475X_band_obs = {'read_noise': read_noise[2], 
                           'ccd_gain': ccd_gain[2],                   
                           'exposure_time': exposure_time[2],
                           'sky_brightness': sky_brightness[2],
                           'magnitude_zero_point': magnitude_zero_point[2],
                           'num_exposures': num_exposures[2],
                           'seeing': seeing[2],
                           'psf_type': 'PIXEL',
                           'psf_model': lens_outputs[psf_lens_index]['multi_band_list'][1][1]['kernel_point_source']   
                          }

lens_model_list = ['SPEMD', 'SHEAR', 'NIE']
kwargs_lens = [{'theta_E': 1.075402182869375, 'e1': 0.14130452695618256, 'e2': -0.054344922343890024, 'center_x': -0.4897334262220723, 'center_y': -0.4874173918839593, 'gamma': 1.9004657358991497}, 
 {'e1': 0.05621848339059133, 'e2': -0.001012628846729346}, 
 {'theta_E': 0.40903435500364377, 'e1': -0.0939768697315022, 'e2': -0.03325148758042043, 's_scale': 1e-10}] 

lens_light_model_list = ['SERSIC_ELLIPSE', 'SERSIC_ELLIPSE', 'SERSIC_ELLIPSE']
kwargs_lens_light_mag_g = [{'R_sersic': 1.9271001282512756, 'n_sersic': 1.3086971828367564, 'e1': -0.2343885121498464, 'e2': -0.01532164101638798, 'center_x': -0.4897334262220723, 'center_y': -0.4874173918839593, 'amp': 3.2643604022473096}, 
                           {'R_sersic': 1.159608361920042, 'n_sersic': 5.828515480768427, 'e1': -0.12991728107230696, 'e2': -0.07214709761226769, 'center_x': -0.4897334262220723, 'center_y': -0.4874173918839593, 'amp': 6.494225311915972}, 
                           {'R_sersic': 0.7100508991041691, 'n_sersic': 6.245883375803998, 'e1': -0.0939768697315022, 'e2': -0.03325148758042043, 'center_x': -0.4115184450909908, 'center_y': -1.4373464403550351, 'amp': 0.24218269573929976}]

    
kwargs_model = {'lens_model_list': lens_model_list,  # list of lens models to be used
                'lens_light_model_list': lens_light_model_list,  # list of unlensed light models to be used
                'source_light_model_list': ['SERSIC_ELLIPSE'],  # list of extended source models to be used
                'point_source_model_list': ['SOURCE_POSITION']  # list of point source models to be used
               }

kwargs_source_mag_g = [{'R_sersic': 0.24063211539441176, 'n_sersic': 1.1368668531035915, 'e1': -0.0645191523449048, 'e2': 0.24308983418569952, 
                        'center_x': -0.4906457423641043, 'center_y': -0.6479828671771817, 'amp': 12.568443559405836}]

kwargs_ps_mag_g = [{'ra_source': -0.4906457423641043, 'dec_source': -0.6479828671771817, 'source_amp': 7.575898373439072}]

numpix = 128  # number of pixels per axis of the image to be modelled

kwargs_F160W_band = util.merge_dicts(HST_camera, HST_F160W_band_obs)
kwargs_F814W_band = util.merge_dicts(HST_camera, HST_F814W_band_obs)
kwargs_F475X_band = util.merge_dicts(HST_camera, HST_F475X_band_obs)

kwargs_numerics = {'point_source_supersampling_factor': 1}

sim_g = SimAPI(numpix=numpix, kwargs_single_band=kwargs_F160W_band, kwargs_model=kwargs_model, kwargs_numerics=kwargs_numerics)
sim_r = SimAPI(numpix=numpix, kwargs_single_band=kwargs_F814W_band, kwargs_model=kwargs_model, kwargs_numerics=kwargs_numerics)
sim_i = SimAPI(numpix=numpix, kwargs_single_band=kwargs_F475X_band, kwargs_model=kwargs_model, kwargs_numerics=kwargs_numerics)

imSim_g = sim_g.image_model_class
imSim_r = sim_r.image_model_class
imSim_i = sim_i.image_model_class

ra_pos, dec_pos, amp, n_points = imSim_g.PointSource.linear_response_set(kwargs_ps_mag_g, kwargs_lens, with_amp=True)
print("x_pos - " + str(np.array(ra_pos[0])*20+64))
print("y_pos - " + str(np.array(dec_pos[0])*20+64))
print("amp - " + str(amp[0]))

![Screen Shot 2019-08-19 at 11 55 04 AM](https://user-images.githubusercontent.com/39751899/63291376-3bffe180-c278-11e9-8471-b8d538cb9cdb.png)

**Comment by sibirrer** [comment]
Hi Vedant,

thanks for the issue and the code. I could reproduce your behavior.
what happened is that there is a forth image highly demagnified (by a factor of 1000) which is hard but not impossible for the numerical solver to find (sometimes it does it, sometimes not). The solver to find the image positions has been applied twice to find the amplitudes and image positions separately in the SimulationAPI mode (which is not necessary). With the latest push to the master branch, there is only one computation done that is self-consistently passed. This should avoid having errors. I don't expect much inaccuracies in not finding a magnitude 1000 demagnified image (e.g. the current solver in default mode does not find the central 5th image in a  power-law profile).

Let me know if you encounter problems, otherwise please close this issue.
Simon

**Comment by Vedant-Sahu** [comment]
Thanks for getting to it so quickly!
