### ISSUE TITLE
Issue with PS rendering (with 0.9.2)

### ISSUE THREAD

**Issue by aymgal** [sibirrer/lenstronomy#127]
I'm having trouble with version 0.9.2 : when I try the following kwargs
```python
kwargs_model = {..., 'point_source_model_list': ['LENSED_POSITION'], 'fixed_magnification_list': [False]} 

#kwargs_params = {..., 'point_source_model': [[{'ra_image': array([-0.9,  0.6,  0.9, -0.7]), 'dec_image': array([-0.9, -0.9,  0.7,  0.9])}], [{'ra_image': array([0.1, 0.1, 0.1, 0.1]), 'dec_image': array([0.1, 0.1, 0.1, 0.1])}], [{}], [{'ra_image': array([-10., -10., -10., -10.]), 'dec_image': array([-10., -10., -10., -10.])}], [{'ra_image': array([10., 10., 10., 10.]), 'dec_image': array([10., 10., 10., 10.])}]]', ...}

kwargs_results = {..., 'kwargs_ps': [{'point_amp': array([266.79773197, 280.07506424, 273.46808759, 265.219639  ]), 'ra_image': array([-0.9204886 ,  0.64522794,  0.85173559, -0.70591383]), 'dec_image': array([-0.83137116, -0.78471491,  0.76415318,  0.82666677])}], 'kwargs_special': {'delta_x_image': array([-0.0010609 ,  0.00510851, -0.00247576,  0.00350916]), 'delta_y_image': array([ 0.00097327, -0.00090853,  0.00016772, -0.00074446]), 'D_dt': 5361.082157276348}, ...}
```

I obtain the following error in [ImSim/Numerics/point_source_rendering](https://github.com/sibirrer/lenstronomy/blob/master/lenstronomy/ImSim/Numerics/point_source_rendering.py#L35) :

**lenstronomy/ImSim/Numerics/point_source_rendering.py", line 35, in _displace_astrometry
    delta_x_new[0:len(delta_x)] = delta_x
ValueError: could not broadcast input array from shape (4) into shape (1)**

I went back to previously called methods, and I found that the method `PointSource.linear_response_set()` returns the `ra_pos` variable as 
```python
ra_pos = [[-0.9204885979919323], [0.6452279400704862], [0.8517355905217909], [-0.7059138349159952]]
```
i.e. separating each individual point source from the _same model_ in lists containing one coordinate. Is it the expected behaviour ? By looking to the `point_source_rendering()` and `_displace_astrometry()` methods, it seems not...

What is strange though is that with version 0.9.0 I didn't have this issue (with the exact same input kwargs), despite having not spotted any obvious changes between 0.9.0 and 0.9.2 (except this new `_displace_astrometry()` method, but I suspect the error is causing prior to this method).

**Comment by aymgal** [comment]
Well in fact, another error occurs afterwards.

This happens when computing the PSF error map, for the amplitudes linear inversion : 

**lenstronomy/PointSource/point_source.py", line 178, in point_source_list
    amp_array.append(amp_list[i][j])
IndexError: too many indices for array**

Kwargs to reproduce this : 
```python

kwargs_model :  {..., 'point_source_model_list': ['LENSED_POSITION'], 'fixed_magnification_list': [False], 'additional_images_list': [False]}

kwargs_params :  {..., 'point_source_model': [[{'ra_image': array([-0.9,  0.6,  0.9, -0.7]), 'dec_image': array([-0.9, -0.9,  0.7,  0.9])}], [{'ra_image': array([0.1, 0.1, 0.1, 0.1]), 'dec_image': array([0.1, 0.1, 0.1, 0.1])}], [{}], [{'ra_image': array([-10., -10., -10., -10.]), 'dec_image': array([-10., -10., -10., -10.])}], [{'ra_image': array([10., 10., 10., 10.]), 'dec_image': array([10., 10., 10., 10.])}]], 'special': [{'delta_x_image': array([0., 0., 0., 0.]), 'delta_y_image': array([0., 0., 0., 0.]), 'D_dt': 1000}, {'delta_x_image': array([0.0005, 0.0005, 0.0005, 0.0005]), 'delta_y_image': array([0.0005, 0.0005, 0.0005, 0.0005]), 'D_dt': 1000}, {}, {'delta_x_image': array([-0.5, -0.5, -0.5, -0.5]), 'delta_y_image': array([-0.5, -0.5, -0.5, -0.5]), 'D_dt': 10}, {'delta_x_image': array([0.5, 0.5, 0.5, 0.5]), 'delta_y_image': array([0.5, 0.5, 0.5, 0.5]), 'D_dt': 12000}], ...}

kwargs_constraints :  {..., 'num_point_source_list': [4], 'point_source_offset': True, 'joint_lens_light_with_point_source': [], 'joint_source_with_point_source': [[0, 0]], 'image_plane_source_list': [False]}
```

The output of [this line](https://github.com/sibirrer/lenstronomy/blob/master/lenstronomy/PointSource/point_source.py#L168) seems to pose an issue (but may be caused by earlier calls), because it there is only one amplitude that is returned, instead of 4 in this case. Not sure to understand how it was different in earlier versions.

If it can help, before [this commit](https://github.com/sibirrer/lenstronomy/commit/1089201e03c4bee857d65955abb0fe5489c6cf46#diff-cb4796cf8f3cc2d2ee00934041705af2), there was no issue for same input.

**Comment by sibirrer** [comment]
Thank you! There was a k=k missing in the input to the amplitudes. Please re-open if there is still an issue and sorry for the bugs introduced

**Comment by sibirrer** [comment]
@aymgal So 'point_amp'=1 in the line you referencing 'just' makes the variable being fixed and not be part of the non-linear sampling. The calculations do not require to know the image amplitudes but in the update passed them and caused an error. I hope I fixed it with the recent push. Please re-open aging. Thanks for the feedback!

**Comment by aymgal** [comment]
@sibirrer Thanks, it is solved.
