### ISSUE TITLE
lensing potential of a truncated NFW profile

### ISSUE THREAD

**Issue by amn3142** [sibirrer/lenstronomy#134]
Line 47 of tnfw.py in LensModel/Profiles, "Todo: truncatedNFW potential not in place yet! " what is nfwPot returning on line 170? It looks like it includes r_trunc as a parameter.

Also is there a different place where we're supposed to put questions? Sorry if so...

**Comment by sibirrer** [comment]
Hi Anna, nfwPot should return the radial potential of the (truncated) NFW profile. To my understanding, this is not properly implemented (as not being used so far). The current function is an approximation that is not accurate enough. @dangilman I am current in this?

and yes, GitHub issues are a right place for this sort of things!

**Comment by dangilman** [comment]
Hi,

I couldn’t figure out the TNFW potential for r<r_s so I just use the NFW
expression and stitch them together at r_s. It should be fairly accurate
since I don’t expect the two potentials differ by much in the regime r<<r_t
but I haven’t quantified it

Daniel

**Comment by amn3142** [comment]
@dangilman just to check, are you using the potential function currently in lenstronomy for your calculations?

**Comment by dangilman** [comment]
Hi, no I don’t use it at all

Daniel

**Comment by sibirrer** [comment]
@dangilman can we make it a raise statement instead as I don't want people to use it until it is tested to be accurate (enough). @amn3142 do you need the lensing potential to predict the time delays for a TNFW profile? Currently no-one has used this for this purpose (to my knowledge)

**Comment by amn3142** [comment]
I don’t need it! Sorry I’m just trying to understand all the steps for going from generating the los halos with pyhalo to solving the lensing with lenstronomy for this powerlaw project I’m working on. I noticed that comment and I wanted to make sure I was looking in the right place for the lensing functions.

**Comment by sibirrer** [comment]
thanks! I renamed the issue and  close it for the moment. Please re-open in case the potential of a TNFW  is requested.
