### ISSUE TITLE
Dimension error in the plotting routine

### ISSUE THREAD

**Issue by martin-millon** [sibirrer/lenstronomy#136]
Here is the error that I got when plotting only one point source in the lens : 

ValueError                                Traceback (most recent call last)
<ipython-input-2-8e32c0b74227> in <module>
      4 
      5 fig, axes = plt.subplots(2, 3, figsize=(16, 8))
----> 6 lensPlot.source_plot(ax=axes[1, 0], deltaPix_source=0.01, numPix=100, with_caustics=False)

~/Desktop/TDLMC/lenstronomy/lenstronomy/Plots/output_plots.py in source_plot(self, band_index, **kwargs)
    362         """
    363         plot_band = self._select_band(band_index)
--> 364         return plot_band.source_plot(**kwargs)
    365 
    366     def error_map_source_plot(self, band_index=0, **kwargs):

~/Desktop/TDLMC/lenstronomy/lenstronomy/Plots/output_plots.py in source_plot(self, ax, numPix, deltaPix_source, center, v_min, v_max, with_caustics, caustic_color, font_size, plot_scale, scale_size, text, colorbar_label, point_source_position, **kwargs)
    793         if point_source_position is True:
    794             ra_source, dec_source = self.bandmodel.PointSource.source_position(self._kwargs_ps_partial, self._kwargs_lens_partial)
--> 795             source_position_plot(ax, coords_source, ra_source, dec_source)
    796         return ax
    797 

~/Desktop/TDLMC/lenstronomy/lenstronomy/Plots/output_plots.py in source_position_plot(ax, coords, ra_pos, dec_pos)
    230     deltaPix = coords.pixel_width
    231     if len(ra_pos) > 0:
--> 232         x_source, y_source = coords.map_coord2pix(ra_pos, dec_pos)
    233         ax.plot((x_source + 0.5) * deltaPix, (y_source + 0.5) * deltaPix, '*', markersize=10)
    234     return ax

~/Desktop/TDLMC/lenstronomy/lenstronomy/Data/coord_transforms.py in map_coord2pix(self, ra, dec)
     62         """
     63 
---> 64         return util.map_coord2pix(ra, dec, self._x_at_radec_0, self._y_at_radec_0, self._Ma2pix)
     65 
     66     def map_pix2coord(self, x, y):

~/Desktop/TDLMC/lenstronomy/lenstronomy/Util/util.py in map_coord2pix(ra, dec, x_0, y_0, M)
    102     #     dec =dec[0] #TODO: dirty fix for a single image, find where the bug is coming from
    103     #     #print (np.shape(np.array([ra, dec])))
--> 104     x, y = M.dot(np.array([ra, dec]))
    105     return x + x_0, y + y_0
    106 

ValueError: shapes (2,2) and (2,1,1) not aligned: 2 (dim 1) != 1 (dim 1)

**Comment by martin-millon** [comment]
And here is my dirty fix on line 99 of Util/util.py that solves the problem, but you probably want something cleaner : 

 # if len(np.shape(np.array([ra, dec]))) == 3 :
    #     #print (np.shape(np.array([ra, dec])))
    #     ra = ra[0]
    #     dec =dec[0] #TODO: dirty fix for a single image, find where the bug is coming from
    #     #print (np.shape(np.array([ra, dec])))

**Comment by sibirrer** [comment]
commit to master solved it
