### ISSUE TITLE
No 3D deprojection for cored-NFW

### ISSUE THREAD

**Issue by aymgal** [sibirrer/lenstronomy#147]
Would it be possible to have the `3d_mass_lens()` in CNFW_ELLIPSE ? To prevent using MGE deprojection.

**Comment by aymgal** [comment]
I'm also noticing that the potential is not properly implemented for the CNFW profile (and thus CNFW_ELLIPSE). I will try to look into this.

**Comment by sibirrer** [comment]
yes indeed. It was not used and the current implementation just gives you a warning. Thanks for doing this. I am in parallel working on the cored density distribution.

**Comment by sibirrer** [comment]
Hi @aymgal the latest commit should have solved this. Also, an implementation of the lensing potential for the CNFW and CNFW_ELLIPSE is also in place. Let me know if there are issues, otherwise please close this issue.

**Comment by aymgal** [comment]
Thanks Simon, actually I had trouble to find an analytical expression for the potential for the cNFW. So indeed I guess you are right to implement it using numerical integrals, if it is numerically accurate enough...
Question then : Do you *think* that simply copying the changes you brought to the cNFW profile (and related files) to lenstronomy v 1.1.0 would work, temporarily ? I ask because there are quite a lot of changes to implement in our pipeline to support lenstronomy 1.2.x and above, and I won't be able to make those changes in the upcoming 2 weeks. Maybe it's kind of impossible to answer though

**Comment by sibirrer** [comment]
hmmm, updating is always a better idea than dragging some features to an older version. I am working now on the design of the hierarchical analysis in the Cosmo.Sampling module that interfaces with the Analysis.td_cosmology features. If you want to use this in the further you anyways have to update to lenstronomy 1.3.x (or 1.4.x in the future).

**Comment by sibirrer** [comment]
I close this issue as the feature is implemented. Please re-open if it is not as desired.
