### ISSUE TITLE
issue in convergence integrals in "deflection_from_kappa_grid_adaptive" : kernel_x and kernel_y not created the same way.

### ISSUE THREAD

**Issue by LyneVdV** [sibirrer/lenstronomy#149]
in LensModel/convergence_integrals.py in the "deflection_from_kappa_grid_adaptive" function, the resulting f_y is not the same as the one calculated with "deflection_from_kappa_grid" (but the f_x is ok). I think it's due to the definition of "kernel_low_res_y"  :
>  kernel_low_res_y, kernel_high_res_y = kernel_util.split_kernel(kernel_y, high_res_kernel_size, low_res_factor)
> kernel_low_res_y /= low_res_factor ** 

Maybe it should be defined the same way as "kernel_low_res_x" : 
> kernel_low_res_x, kernel_high_res_x = kernel_util.split_kernel(kernel_x, high_res_kernel_size, low_res_factor, normalized=False)

**Comment by sibirrer** [comment]
ouh, should have tested the y-direction too. Indeed there was a bug in this. Thank you for pointing this out! The last push to the master branch should have resolved it. Please reopen if still failing.
