### ISSUE TITLE
MCMC sampler does not work with MPI=False and threadCount > 1

### ISSUE THREAD

**Issue by aymgal** [sibirrer/lenstronomy#166]
The `schwimmbad.choose_pool` method, when `mpi=False` and `threadCount` > 1 returns a MultiPool object that has no `is_master` attribute, hence the following error :
```python

  File "/Users/aymericg/Documents/EPFL/PhD_LASTRO/Code/Forked/lenstronomy_forked/lenstronomy/Workflow/fitting_sequence.py", line 94, in fit_sequence
    mcmc_output = self.mcmc(**kwargs)
  File "/Users/aymericg/Documents/EPFL/PhD_LASTRO/Code/Forked/lenstronomy_forked/lenstronomy/Workflow/fitting_sequence.py", line 230, in mcmc
    threadCount=threadCount, progress=progress)
  File "/Users/aymericg/Documents/EPFL/PhD_LASTRO/Code/Forked/lenstronomy_forked/lenstronomy/Sampling/sampler.py", line 149, in mcmc_emcee
    if pool.is_master():
AttributeError: 'MultiPool' object has no attribute 'is_master'

```

In addition,  I see that the new schwimmbad way of dealing with pools calls the `multiprocessing` module instead of the `multiprocess`, as it was done before in lenstronomy, and which is more robust because of pickling issues in `multiprocessing`. @ajshajib , could you please look into that since you introduced this change ?

I did not test for the PSO, but it's likely to give the same result.

In the meantime, I will temporarily make my own fork of schwimmbad to fix that, but it's not viable to link lenstronomy to this fork.

**Comment by sibirrer** [comment]
@aymgal do you satisfy the requirements as indicated in requirements.txt? @ajshajib added a temporary fix to a specific commit of schwimmbad. Just checking not to duplicate efforts in this direction.

**Comment by aymgal** [comment]
Yes I do, I took the last github version of schwmimbad as required. The schwimmbad multithreading pool has no `is_master` attribute.

**Comment by ajshajib** [comment]
Would it be preferable if we open an issue for schwimmbad to add an `is_master` method for the `MPIPool` class? After all, the philosophy of schwimmbad is to make switching pools between single-processor, multithreads, and MPI seamless.

The pickling issue between multiprocess and multiprocessing can be resolved by using `use_dill=True` in `choose_pool`.  multiprocessing is a default Python 3 package, whereas multiprocess just forks multiprocessing to use dilll. It's the same author(s) for both multiprocessing and dill.

I think, the ideal solution would be to let schwimmbad do it's job and not having to manually create a `Pool` object within lenstronomy, just like emcee does it.

**Comment by ajshajib** [comment]
To clarify, `use_dill=True` only takes care of pickling for MPI. I have not used multi-threading recently, so I do not know if there will be pickling issue in such.

**Comment by sibirrer** [comment]
do we need a is_master() functionality in multithreading? If not, I could make the changes within lenstronomy. Thanks

**Comment by sibirrer** [comment]
@ajshajib yes, but we might get conflicts then between MPI fixes and multi-threading.

**Comment by ajshajib** [comment]
`is_master()` is only used to avoid multiple message printing. I am not sure, if duplicate messages can be printed in multi-threading mode. If not, it is certainly easy to change relevant lines to `if mpi and pool.is_master():` which will avoid calling `is_master()` for non-MPI cases.

**Comment by aymgal** [comment]
Yes in parts where a multithreading pool is running, you can get multiple prints.

dill is also useful to have in multithreading mode, but the schwimmbad MultiPool does not have the option to use dill instead of multiprocessing, like it is the case for the MpiPool

**Comment by ajshajib** [comment]
Have you run into pickling issue with schwimmbad `MultiPool`, if you can do a quick test after commenting out the line with `is_master()`?

**Comment by sibirrer** [comment]
@aymgal: does the PSO work with multithreading? I'd expect the same issue to occur.
@ajshajib : is your schwimmbad commit which is in the requirements on lenstronomy merged into the master of schwimmbad? Please track this as a separate issue or submit a PR that sets the schwimmbad requirement to master. This would prevent us from development with schwimmbad. Thanks.

**Comment by ajshajib** [comment]
> @ajshajib : is your schwimmbad commit which is in the requirements on lenstronomy merged into the master of schwimmbad? Please track this as a separate issue or submit a PR that sets the schwimmbad requirement to master. This would prevent us from development with schwimmbad. Thanks.

Yes, my commits are part of the master branch. In the requirements.txt, it is possible to simply point the master branch. I just pointed to the specific PR merge commit, just in case bleeding edge commits to the master branch of schwimmbad may break lenstronomy.

**Comment by sibirrer** [comment]
@ajshajib @aymgal please use the branch multithreading_mpi to suggest changes in lenstronomy.

**Comment by aymgal** [comment]
@sibirrer yes same for the PSO. Actually an issue arises even earlier as the choos_pool when threadCount > 1 calls use_drill, but this parameters does not exist in MultiPool : 
```python
TypeError: __init__() got an unexpected keyword argument 'use_dill'
```

@ajshajib for my specific case right now it works without dill (so the only thing I did is add the is_master method). I just remember that some months ago, I had pickling issues in multithreading that I solved using dill.

**Comment by ajshajib** [comment]
@aymgal Can you kindly suggest the changes first? It should be easier for you, as you seemingly have test cases to run already.  I can comment on the changes based on my recent experiences of dealing with MPI.

**Comment by aymgal** [comment]
Ok no problem, but what's your preference @sibirrer ? I propose a change to schwimmbad master branch, or I write a "hack" in lenstronomy ?

**Comment by sibirrer** [comment]
> Ok no problem, but what's your preference @sibirrer ? I propose a change to schwimmbad master branch, or I write a "hack" in lenstronomy ?

up to you @aymgal. It would be great if we can minimize outside dependence on 'unstable' development. If you implement it in lenstronomy, I would not call it a 'hack' if you well document the in- and outputs, its current purpose and reason for doing it there.

**Comment by sibirrer** [comment]
@aymgal I give you collaborator access to lenstronomy. Please use it only to push to development branches and make PR's, thank you!

**Comment by aymgal** [comment]
Ok thanks @sibirrer , I'll prepare the changes

**Comment by aymgal** [comment]
I pushed a fix : https://github.com/sibirrer/lenstronomy/commit/f5086af01b9bccf6185c22b6f2d5c7e889c1f27e

Not sure where to put the method `choose_pool` though.

**Comment by sibirrer** [comment]
I close this issue for now based on merge #167 . Please re-open in case of remaining issues. Thank you!
