### ISSUE TITLE
Is this empty list necessary to be returned?

### ISSUE THREAD

**Issue by ajshajib** [sibirrer/lenstronomy#168]
https://github.com/sibirrer/lenstronomy/blob/375476bc60fb6997a82b170d7714de0063642fe2/lenstronomy/Sampling/sampler.py#L147

When I changed the corresponding method recently, I kept the format of the return values intact with an empty list being returned at the end. I'm now working on a method in dolphin that would save the fit outputs in hdf5 format, and stumbled upon this again. Is there a reason for keeping the empty list in the return values?

**Comment by sibirrer** [comment]
no, not anymore. There was in the past when I had joint output formats for PSO and MCMC, which is not the case anymore.

**Comment by ajshajib** [comment]
Great. It's actually fine with me (or dolphin) to leave it like that, but it's also fine if you want to take it out.

**Comment by sibirrer** [comment]
I'll take it out right away (and add some needed documentation), done is done

**Comment by ajshajib** [comment]
That would be great, thanks!

**Comment by sibirrer** [comment]
I used 'master branch privileges' to fix this :). Please re-open if you need to change something. Thanks.
