### ISSUE TITLE
clear distinction of public and private definitions

### ISSUE THREAD

**Issue by sibirrer** [sibirrer/lenstronomy#17]
@dangilman 
make sure only routines, that a user should access and we can assure those are sustainable and "long time supported and backwards compatible" are public functions. All other definitions (including parameters actually) should be _private.
Sorry to be a bit picky here. As this sub-package is now part of lenstronomy, new releases have to be backwards compatible and people will contact me if their routines and wrappers do not work anymore.

**Comment by dangilman** [comment]
I've set the majority of non-user functions and class variables to "_variable" format

**Comment by sibirrer** [comment]
you can close any issue that you consider to be no issue anymore :-)

**Comment by dangilman** [comment]
Haha yeah I’m trying to figure out how to actually close it…

**Comment by sibirrer** [comment]
hmm, maybe you don't have the right. Though you can add it in the pull request: See
https://help.github.com/articles/closing-issues-using-keywords/
