### ISSUE TITLE
Unused feature in MCMC sampling ?

### ISSUE THREAD

**Issue by aymgal** [sibirrer/lenstronomy#172]
I was looking for a way to start MCMC from a previous chain that has not converged yet (to prevent re-run it entirely), and saw that. I guess it was an old feature no more supported, or do I miss something? I think `initpos` is never used afterwards.

https://github.com/sibirrer/lenstronomy/blob/58feb5df54972cf37c6e3ce2f522b16dd357661f/lenstronomy/Workflow/fitting_sequence.py#L220

Does emcee allows to start a new sampling while not loosing the history of a previous run ?

**Comment by sibirrer** [comment]
The ReusePositionGenerator() was specific to CosmoHammer. I can move this also to emcee as a start position argument, should not be too hard
fyi: emcee had developed a nice backend feature, which might also be useful:
https://emcee.readthedocs.io/en/stable/tutorials/monitor/
Or do you want to have a go on this? Just asking :)

**Comment by aymgal** [comment]
Thank your Simon for the commit.
Indeed the backend file feature of emcee looks interesting. If it appears to be useful for my work, I may propagate it to lenstronomy in the future.
