### ISSUE TITLE
Strange values of physical NFW parameters 

### ISSUE THREAD

**Issue by LyneVdV** [sibirrer/lenstronomy#177]
I wanted to know the virial mass and virial radius of an NFW with parameters Rs=0.3 (arcsec) and alphaRs=3. I used LensCosmo.nfw_angle2physical the following way :

import lenstronomy.Cosmo.lens_cosmo as lc
lens_c = lc.LensCosmo(z_lens=0.271, z_source=2.0)
print(lens_c.nfw_angle2physical(0.3,3.0))

The answer is (1.568110506577227e+19, 0.0012594231683317368, array(1.56206978e+09), 1967306.8702234358, 1.746662500411441e+33) (using lenstronomy v1.2.2)
(for rho0, Rs, c, r200, M200 respectively). If I understand correctly that would mean M200=1.7e33 M_sun , R200= 2.0e6 Mpc , c=1.6e9 , Rs=0.00126 Mpc (corresponding to 0.3 arcsec -> ok), rho0 = 1.6e19 (is the unit M_sun/Mpc^3 ?).  Those values doesn't make sense physically speaking I think. 

My question is the following : did I miss something in the use of lenstronomy functions or is a NFW with Rs=0.3 and alphaRs=3. unphysical (and that's why the answer is unphysical) or is there an issue in the nfw_angle2physical() function ?

**Comment by sibirrer** [comment]
Hi Lyne, an NFW profile with 3 arc second deflection angle at 0.3 arc seconds from the center is unphysical in the sense that it requires a lot of mass within an aperture of 0.3 arc seconds. Then considering that the inner slope of the NFW is rather shallow (-1) this in turn requires a large extrapolation (and thus mass). Once you have exceeded 10^15 M_sun mass, the M(c) relation may also break down and becomes unstable. So yes, this is a regime where the NFW parameterization with the M(c) relation imposed breaks down. There is also the inverse function `nfw_physical2angle(self, M, c)` and you can see the extreme 'reasonable' ranges in this relation.

**Comment by LyneVdV** [comment]
Thanks Simon !
