### ISSUE TITLE
Issue in error_map_source plot when using multiband 

### ISSUE THREAD

**Issue by aymgal** [sibirrer/lenstronomy#182]
I think there is a small bug in the `error_map_source_plot` routine, when using multi-band/multi-exposure is used. The function below
https://github.com/sibirrer/lenstronomy/blob/edf82234d4c3c72f158d720086922f41b52588d7/lenstronomy/Plots/model_band_plot.py#L345
is given as input band-selected kwargs, but this function itself tries to select the right kwargs as well, so I get a index-out-of-bound error.
Not urgent at all for me however, since I'm still not sure how to interpret this plot, I can just not use it for now.

**Comment by sibirrer** [comment]
Thanks for pointing this out. I made (hopefully) a fix to it with the last commit. Please close the issue if fixed or let me know if it does not work.

**Comment by aymgal** [comment]
It is fixed, thanks!
