### ISSUE TITLE
check_positive_flux flag applied to multiple bands

### ISSUE THREAD

**Issue by sibirrer** [sibirrer/lenstronomy#187]
checking whether the linear inversion leads exclusively positive amplitudes is currently only applied to the last inversion step and does not check in sequence.

**Comment by sibirrer** [comment]
@martin-millon  @aymgal  I made an update to the master branch that now applies the check for non-negative amplitudes for all bands. Let me know if you experiencing issues. I close this issue for now but please re-open it if there is something not working as desired. Thanks

**Comment by martin-millon** [comment]
Thanks @sibirrer for the update, I will need this very soon. I'll let you know if there are any issues.

**Comment by aymgal** [comment]
Same, thank you @sibirrer !
