### ISSUE TITLE
multiprocess is not a required package for lenstronomy

### ISSUE THREAD

**Issue by swagnercarena** [sibirrer/lenstronomy#188]
In version 1.5.0 of Lenstronomy, multiprocess is now used. pip installing lenstronomy does not require the package multiprocess to be installed, causing an error if the fitting sequence code is called. 

https://github.com/sibirrer/lenstronomy/blob/b43b5478c9fc9d40e0d2116190960ec4d8524601/lenstronomy/Sampling/Pool/multiprocessing.py#L15

**Comment by sibirrer** [comment]
multiprocess>=0.70.8
is specified in the requirements.txt file. Is the installation not reading it? Travis-ci is installing it and can execute the import statement.

**Comment by swagnercarena** [comment]
It did not install multiprocess when I ran pip install lenstronomy --upgrade. I also tried installing a fresh version of lenstronomy in a new conda environment and ran into the same issue (no multiprocess).

**Comment by sibirrer** [comment]
I would need more details to reproduce your behavior. Is another version of multiprocess<0.70.8 pre-installed? Did you start from an empty environment? Python version as specified by lenstronomy tests? I can only consider this as a lenstronomy issue when starting from an empty environment within the python versions specified.

**Comment by swagnercarena** [comment]
I did start from an empty environment (without multiprocess installed at all) and ran into the same issue. I was using python version 3.7.6. It looks like in your setup.py file there isn't any reference to the requirements.txt file. The only requirements specified there are scipy, numpy, and configparser. The travis.yaml file instead does specifically run the install using pip install -r requirements.txt, which installs multiprocess (along with a number of other dependencies). Maybe this is a misunderstanding on my part, but I believe if the user just runs:
` pip install lenstronomy --user `
as is suggested in the readme, they will be missing packages like multiprocess.

**Comment by sibirrer** [comment]
Ah, I see. The current convention (they way I interpret it, is only have the 'base' requirements in the install_requirements and other parts that might not been used by all users as 'optional' in the requirements.tex. See e.g. https://packaging.python.org/discussions/install-requires-vs-requirements/
I may consider adding more packages to the install_requirements but also don't want to over-load it.
