### ISSUE TITLE
Discrepancy in documentation of `LensCosmo.sigma_crit()`

### ISSUE THREAD

**Issue by ajshajib** [sibirrer/lenstronomy#191]
https://github.com/sibirrer/lenstronomy/blob/de2c1b9f8b745fe99fe2c96c5e56baa3af22024b/lenstronomy/Cosmo/lens_cosmo.py#L75

This function returns critical density in M_sun/Mpc^2 unit, but the docstring says the unit is M_sun/rad^2.

**Comment by sibirrer** [comment]
My bad, yes this was mistakenly left unchanged. Thanks a lot for pointing this out! Did this cause you major issues to classify it as a bug? I updated the documentation. If this solves your issue, please close it.

**Comment by ajshajib** [comment]
No, it didn't cause me major issues, just the numbers were weird at first, so I checked the code to find out the correct unit. I didn't intend this to be a bug report, rather a request to update the documentation for future users.
