### ISSUE TITLE
Error in Gaussian light profile normalization

### ISSUE THREAD

**Issue by amn3142** [sibirrer/lenstronomy#193]
In line 25 in lenstronomy/lightModel/Profiles/gaussian.py in the Gaussian class 'function' function, the normalization is
    c = amp / (2 * np.pi * sigma**2)
It should be 
      c = amp / (2 * np.pi * sigma**2)**0.5

This also appears to be an issue in the mass profile definition.

Sorry if I'm just missing somewhere where it's corrected later.

**Comment by sibirrer** [comment]
Hi @amn3142 , the profile amplitude is defined such that the 2D integral leads to the value specified in 'amp'. The same notation is also used in the mass profiles. I made the light model Gaussian profile description more clear (I hope) with the latest commit (referenced here). Let me know if you have further questions or close the issue. Thank you!

**Comment by amn3142** [comment]
Ah yes... two dimensional... face palm....
