### ISSUE TITLE
Noise covariance not updated

### ISSUE THREAD

**Issue by aymgal** [sibirrer/lenstronomy#208]
Quick issue I encountered recently: when updating the data array of an `ImagingData` instance, the `self._C_D` should be updated as well.
The issue can arise when the `self.C_D()` method gets called before updating the data array, hence setting the attribute `self._C_D`. The attribute is currently not deleted / updated when calling `self.update_data()`, which can cause inconsistency between the (new) data array and the (old) covariance matrix.
I can propose very easily a fix, but wanted to properly formulate it here beforehand.

**Comment by sibirrer** [comment]
I can quickly do it and move `update_data` to the` ImageNoise` class (which is inherited). Then it's easier to update/delete a previous private variable defined in this class. The API does not change. Is this ok for you?

**Comment by aymgal** [comment]
Yes thank you!

**Comment by sibirrer** [comment]
I had to keep it in the same class due to `_nx` and `_ny` variables. If it solves your issue, please close it - thank you!

**Comment by aymgal** [comment]
Perfect! thanks
