### ISSUE TITLE
Issues with multiprocess

### ISSUE THREAD

**Issue by chinyitan** [sibirrer/lenstronomy#250]
I having some issues with `multiprocessing` where on some clusters the PSO will not start even waiting for a hour. When I manually interrupt the code, I found that the code is stuck at the following block:

<img width="817" alt="Screenshot 2021-04-02 at 8 24 26 am" src="https://user-images.githubusercontent.com/55915948/113419351-ec0e5980-938c-11eb-9843-7377d4454235.png">

**Comment by sibirrer** [comment]
Hi @Ywyh12345 , thanks for reaching out!
From the error message, I deduce that you are using the option multi-threading without MPI. 
The code is effectively waiting for some other jobs to be done but does not receive the expected input from other cores to continue.

On clusters, multi-threading might not be available between cores of different nodes as they are physically separated (and so also the memory). I recommend using the MPI option to run jobs on cluster. You have the option in the FittingSequence() to set mpi=True and you need the job to be launched with MPI support.

**Comment by ajshajib** [comment]
I think @Ywyh12345 is not using a "cluster" with MPI, it is one machine with large number of CPUs.

**Comment by sibirrer** [comment]
then it might be system-dependent, in particular what version of the dependent software is installed. Can you check that the system, where you run into problem, satisfies these requirements: https://github.com/sibirrer/lenstronomy/blob/main/requirements.txt
Another issue might be memory requirements, such that there is not enough memory for all the parallel processes. But my first guess would be is that the multi-threading is not supported on these machines. Can you also run a short PSO run on a single core? This might help debugging other issues and estimating memory and scaling properties. Error messages in multi-threading modes are not always so obvious and transparent.

**Comment by Ywyh12345** [comment]
Thanks @sibirrer for the quick reply. I have checked that the system satisfied all the requirements but the problem still persist.

The code run perfectly on a single core. Moreover, it has no problem running the "Quadrupoly lensed quasar modelling" example notebook even with multiple cores. 

I even have an informal fix for the problem when I would run the Quadrupoly example notebook then the galaxy-galaxy lens PSOs in the same notebook and that allows the code run for multiple cores

**Comment by sibirrer** [comment]
Thanks for the info @Ywyh12345 !This sounds a bit weird to me. There might be different imports and options chosen in the two different notebooks. The only difference of the quad model notebook relative to the simple ring case I can imagine is that likelihood evaluation of the simple ring is much faster, potentially causing overhead in the distribution to different threads/cores. I also normally don't run much multi-threading jobs through a notebook as these threads might start occupying the same cores eventually, and this may or may not be well managed by your OS. If you have a specific error that can be reproducible cross-system, you could post the entire script here, such that I can try to reproduce it.

**Comment by Ywyh12345** [comment]
I don't think I can reproduce the specific error in my local MacOS device, so the problem seem to be specific to the cluster

**Comment by ajshajib** [comment]
Yes, I too thought this is pretty weird, since the notebook runs just fine with a single core, and then multicore works for another notebook but not in the particular notebook @chinyitan was working with. I asked @chinyitan to post it here in case someone might have faced a similar issue before and found out a solution. Probably @aymgal and/or @martin-millon have used `multiprocess` for lenstronomy quite substantially.

A workable solution for @chinyitan could be to install mpi4py to use the MPI feature to access multiple cores, although it's just one single machine.

**Comment by martin-millon** [comment]
Yes, I am only using multithreading and not MPI on the EPFL cluster since I have access to only one node at a time. I found that the multithreading mode is more efficient if you are using only one node. But I never had this problem on the cluster, nor on my laptop...

**Comment by chinyitan** [comment]
I manage to solve the issue by using mpi4py

**Comment by sibirrer** [comment]
Thanks for the note @chinyitan and I am glad you could resolve it! 
Is it basically that the when you chose the MPI option within lenstronomy that things worked or did you have another work-around?
Would you mind adding the fix/solution to your problem for prosperity of this issue? This might benefit others as well. Thank you!

**Comment by chinyitan** [comment]
Yes, the only change I did was to chose the MPI option within lenstronomy instead of multiprocessing, and I didnt have to try any other work around for it to work.

Is there anything else I can do to add my fix to the issue or is the comments sufficient?

**Comment by sibirrer** [comment]
thanks! No, that's great to know and having it stated in this closed issue.
