### ISSUE TITLE
joint constraints not working

### ISSUE THREAD

**Issue by rkkuang** [sibirrer/lenstronomy#254]
Hi @sibirrer , 
the related parameters I used are:

```
lens_model_list = ['PEMD', 'SHEAR']
lens_light_model_list = ['SERSIC']
```
I have set:
`kwargs_constraints = {'joint_lens_with_light': [[0, 0, ["center_x", "center_y"]]] }`

and then run the PSO fitting, the best fit parameters are:

```
{'kwargs_lens': [{'theta_E': xx,
   'gamma': xx,
   'e1': xx,
   'e2': xx,
   'center_x': -0.0021318479304256147,
   'center_y': -0.041543362303880754},
  {'gamma1': xx,
   'gamma2': xx,
   'ra_0': xx,
   'dec_0': xx}],
 'kwargs_lens_light': [{'amp': xx,
   'R_sersic': xx,
   'n_sersic': xx,
   'center_x': -0.11652584688639721,
   'center_y': 0.16484505843143626}],
}
```

The corresponding source code to handle joint constraints is in https://github.com/sibirrer/lenstronomy/blob/main/lenstronomy/Sampling/parameters.py

I am not sure why the "center_x", "center_y" are not the same for the 'PEMD' mass and "SERSIC" light in my case.

Thanks!

**Comment by sibirrer** [comment]
Hi @rkkuang ! I guess you are using a quad (or double) modeling option where the point source constraints are imposed by a non-linear solver of some lens model parameters. This means that some of the parameters (such as the lens center) are not sampled directly but instead inferred by a non-linear solver given the image positions (which are sampled instead). This then does not allow to join the lens model arguments with the option directly. On the solver, I updated some of the description recently in this notebook: https://github.com/sibirrer/lenstronomy_extensions/blob/main/lenstronomy_extensions/Notebooks/quad_model.ipynb and for details about general point source modeling options can be found here: https://github.com/sibirrer/lenstronomy_extensions/blob/main/lenstronomy_extensions/Notebooks/catalogue%20modelling.ipynb 

To fix (or approximately fix) the lens and light parameters, I recommend using a tight custom prior to be added in the sampling that demands and punishes the likelihood in that regard. An example is in box 5 of this notebook: https://github.com/sibirrer/lenstronomy_extensions/blob/main/lenstronomy_extensions/Notebooks/td_modeling_external_lens_likelihood.ipynb with kwargs_likelihood['custom_logL_addition']. The other option is to remove the non-linear solver and add a punishing term in the misrepresentation of the solution of the lens equation to map to the same source plane.

This is a bit a technical aspect, but the non-linear solver comes with a great speed-up/convenience for the sampling.

**Comment by rkkuang** [comment]
Thank you @sibirrer ! Then I will use "custom_logL_addition".
