### ISSUE TITLE
about convolution in ImageModel.image

### ISSUE THREAD

**Issue by rkkuang** [sibirrer/lenstronomy#259]
Hi all, sorry to ask again,

I am simulating a lensed quad system with a PIXEL type psf, the output is different from what is expected:
![simu_res_psf shape51](https://user-images.githubusercontent.com/40119865/120911594-282aa700-c6bb-11eb-88a4-bba84032af00.png)
The code to generate the lower right panel is:
`imageModel_PIXEL = ImageModel(data_class2, psf_class_PIXEL, lens_model_class, source_model_class, lens_light_model_class=None, point_source_class=None, kwargs_numerics=kwargs_numerics)

image_sim_PIXEL = imageModel_PIXEL.image(kwargs_lens, kwargs_source, kwargs_lens_light, unconvolved=False)`

with 

`kwargs_numerics = {'supersampling_factor': 1, 'supersampling_convolution': False, "convolution_type" : "grid", "compute_mode": 'regular'}`

The lower right panel can also be generated with:
`from lenstronomy.ImSim.Numerics.numerics_subframe import NumericsSubFrame
from lenstronomy.ImSim.image2source_mapping import Image2SourceMapping

ImageNumerics = NumericsSubFrame(pixel_grid=data_class2, psf=psf_class_PIXEL, **kwargs_numerics)
ra_grid, dec_grid = ImageNumerics.coordinates_evaluate
source_mapping = Image2SourceMapping(lensModel=lens_model_class, sourceModel=source_model_class)

source_light = source_mapping.image_flux_joint(ra_grid, dec_grid, kwargs_lens, kwargs_source, k=None) 
source_light_final = ImageNumerics.re_size_convolve(source_light, unconvolved=False)`

I have read the related lenstronomy source codes, e.g.
https://github.com/sibirrer/lenstronomy/blob/main/lenstronomy/ImSim/Numerics/convolution.py

Since the "convolution_type" is already set to be "grid", the two images in the lower panel are expected to be the same.
Are there some extra operations on the image or on the psf?

(If I use other types of psf, e.g. gaussian, elliptical gaussian, the results are fine, i.e. results from scipy and lenstronomy are the same.)

Thanks!

**Comment by rkkuang** [comment]
Hi, the reason is that the psf is normalized first.

**Comment by sibirrer** [comment]
I clarified a bit that the kernel is being normalized. If you have other suggestions for clarifying what is going on, please let me know!
