### ISSUE TITLE
The conf_default.yaml is not installed properly

### ISSUE THREAD

**Issue by Jerry-Ma** [sibirrer/lenstronomy#278]
When installed via `pip`, The file `conf_default.yaml` is missing in `site_packages/lenstronomy/Conf`.

**Comment by sibirrer** [comment]
Hi @Jerry-Ma , which lenstronomy version do you have installed? Version 1.9.0 (latest on pypi does) contain the conf_default.yaml file

You can check the version with
$import lenstronomy
$lenstronomy.__version__

Make also sure that when you have multiple version of lenstronomy that the latest version is linked to the python path.

**Comment by Jerry-Ma** [comment]
umm, I installed the development version using `pip install git+https://github.com/sibirrer/lenstronomy.git`.
I just confirmed that `pip install lenstronomy` works properly.

**Comment by sibirrer** [comment]
hmm, the latest stable version on GitHub should also work since it's only marginally different to what is currently on PyPi. Perhaps there were issues with different versions of lenstronomy in your path if you had installed older versions as well. Might be worth uninstalling first all versions before installing the one you want.
btw: if you plan to develop/code/change lenstronomy, I'd recommend you to fork the version, as described here: https://github.com/sibirrer/lenstronomy/blob/main/CONTRIBUTING.md

**Comment by Jerry-Ma** [comment]
I tested the installation in a freshly created virtualenv, so it is unlikely due to interfering with older versions.

I think it may be related to how the package data is specified in the setup.py. I'll see if I can spend some time to find a fix.

**Comment by sibirrer** [comment]
One fix could be that you install lenstronomy after manual cloning with

`$python setup.py install --user`

The integrated testing on travis-ci is using probably a similar command as you and there it works (from the main branch of lenstronomy)

**Comment by Jerry-Ma** [comment]
@sibirrer Yep I found a fix by adding an entry in the Manifest.in file, according to https://setuptools.readthedocs.io/en/latest/userguide/datafiles.html. No sure why this issue is happening only for the `pip install git+https://github.com/Jerry-Ma/lenstronomy.git` but not `pip install lenstronomy`. My fix is here https://github.com/Jerry-Ma/lenstronomy/commit/85987ab3f14b7b434842111a3399edba2c35623c.

**Comment by sibirrer** [comment]
Thanks for the info and fix @Jerry-Ma ! Would have cloning locally and then `$python setup.py install --user` also had worked? Just curious. Do you mind making a pull request for this change into my repo? That would be great if someone else encounters the same issue. Thanks a lot!

**Comment by Jerry-Ma** [comment]
@sibirrer 

Sorry for my not being able to reply timely. Just saw that you've merged the change. Thanks a lot!
