### ISSUE TITLE
PSF error map specification for supersampled PSF

### ISSUE THREAD

**Issue by ajshajib** [sibirrer/lenstronomy#294]
If a user provides a supersampled PSF, then it is not clear what the size of the error map should be, as the supersampled PSF is downsampled internally by `lenstronomy` and the downsampled size is not always consistent with the provided supersampling factor. Ideally, the provided error map can be expected to match with the supersampled PSF and `lenstronomy` should be able to downsample the error map as well. Also, it may be helpful to put a warning/error message if a user tries to iteratively reconstruct a supersampled PSF, as that’s not the expected usage at present.

**Comment by sibirrer** [comment]
PR #295 addresses the documentation issue. Further development in the functionality might still be needed/desired
