### ISSUE TITLE
Incompatibility with Astropy Version 5

### ISSUE THREAD

**Issue by smericks** [sibirrer/lenstronomy#303]
Hi, I noticed that you recently removed astropy<5 in requirements.txt. I tried to use astropy version 5 with lenstronomy, and ran into the following error. I reverted back to astropy version 4.3 to fix the error.

from lenstronomy.Cosmo.cosmo_interp import CosmoInterp
  File "/home/users/sydney3/.local/lib/python3.9/site-packages/lenstronomy/Cosmo/cosmo_interp.py", line 1, in <module>
    from astropy.cosmology.core import vectorize_if_needed, isiterable
ImportError: cannot import name 'vectorize_if_needed' from 'astropy.cosmology.core' (/home/users/sydney3/.local/lib/python3.9/site-packages/astropy/cosmology/core.py)

It appears that vectorize_if_needed is no longer defined in astropy/cosmology/core.py

**Comment by sibirrer** [comment]
Hi @smericks , astropy v5 is only compatible with the current main branch. Your error message is not consistent what has changed to make astropy v5 compatible. Make sure you pull the latest version from GitHub for the moment and that lenstronomy is installed in development mode to adopt the changes.
