### ISSUE TITLE
Small error while installing the most recent lenstronomy

### ISSUE THREAD

**Issue by Maverick-Oh** [sibirrer/lenstronomy#304]
Hello Simon,
I was re-installing lenstronomy for some reason and in the process of installation, I saw this minor error
"""
  File "build/bdist.linux-x86_64/egg/lenstronomy/Cosmo/_cosmo_interp_astropy_v5.py", line 47
    def _integral_comoving_distance_z1z2_scalar(self, z1, z2, /):
                                                              ^
SyntaxError: invalid syntax
"""
The ^ sign is supposed to be under / sign.
I think there is a typo? Please check. Thanks!

**Comment by sibirrer** [comment]
Hi @Maverick-Oh , thanks for posting this issue! Which Python version are you using? lenstronomy (and astropy) is not supporting Python2 anymore, and this syntax '/' in the function argument might not be supported in Python 2. The '^' in the error message is just indicating the line of code that raises the error.

**Comment by sibirrer** [comment]
I just found out that the syntax is only supported for Python versions >3.7, which is not desired (I used this code block from the astropy v5 release), see https://www.python.org/dev/peps/pep-0570/ for details. I will remove the syntax. Do you need a new pip release version immediately to run your code or can you use the main branch?

**Comment by Maverick-Oh** [comment]
Hi Simon!

It is nothing urgent to me. Thanks for checking up on it!

Thanks!
Maverick

**Comment by sibirrer** [comment]
lenstronomy release version v1.9.3 should have addressed this issue. Please open the issue again if there is a remaining problem with it.
