### ISSUE TITLE
Help needed for better results 

### ISSUE THREAD

**Issue by Jibzkun** [sibirrer/lenstronomy#319]
Hello, since a few months I've been trying to model a strong lens from the SLACS whith Lenstronomy for my physics degree ( I mean I'm a newcomer) , but I have some convergence issues with some parameters... 
Indeend "n_sercic_lens_light" is always going to the upper limit (10 here), it's the same for few others ( "e1_source_light0" , "R_sercic_source_light0", ...) as you can see on the image. Even if I put the upper limit higher, some parameters will reach it. 
Sometime parameters don't reach the higher but the lower limit. More over, the shear result is always scattered... I don't understand why I have those issues...  there is definitely something not right in my program, something I  did wrong probably.
Does anyone have time to spare to help me  :) ?

![lens_reconstructed_2](https://user-images.githubusercontent.com/98708226/166154794-3fae39ef-5f5c-45e9-9b77-bb6bab6adc98.png)
![lens_reconstructed](https://user-images.githubusercontent.com/98708226/166154797-fad8ee94-10f4-4190-a0bd-79fbce5ce3a6.png)
![parameters_results](https://user-images.githubusercontent.com/98708226/166154798-71f4970c-4770-46b0-8b0b-c9f990d8e788.png)

**Comment by sibirrer** [comment]
Hi @Jibzkun , thanks for posting this issue!
A few things I spotted from the plots:
- The reduced residuals are very low (at 0.04 or below). This indicates a fast overestimation of the statistical errors in your modeling (background noise and possibly even the Poisson noise with the exposure time). It is important that the noise properties are correct. There should be a scatter in the of +- 1 in empty patches. A perfect fit has a random white noise scatter of +-1 everywhere (and a reduced chi2=1). You need to fix this before looking at the other issues.
- A large n_sersic=10 is numerically unstable, such that you have almost a point-like component in the center. I think I can spot a pattern of the PSF in the residual map. I would bound n_sersic a bit lower
- There is clearly some morphological structure in the source galaxy that a single Sersic function is unable to describe. So don't expect a perfect fit with it. You can, for example, add Shapelets source light components in the modeling.
- The same for the lens light. Often, a single Sersic light profile might not be sufficient. You can, for example, overlay two Sersics with joint centroids.
- Your mcmc chains clearly have not converged.
- You might find some inspiration from [dolphin](https://github.com/ajshajib/dolphin) by @ajshajib 

If you want, you can join the lenstronomy Slack channel for this type of questions and inquiries. Just send me your email address and I can add you.

Best,
Simon

**Comment by Jibzkun** [comment]
Thank's for all your advices, I will try to fix my noise and psf issues, indeed it could be interesting to join the lenstronomy Slack channel to optimise my results.  Do you want me to sent you my email adress in this section ?

**Comment by sibirrer** [comment]
> Thank's for all your advices, I will try to fix my noise and psf issues, indeed it could be interesting to join the lenstronomy Slack channel to optimise my results. Do you want me to sent you my email adress in this section ?

Up to you. You can also send me an email. My email address should be stated on my website (also linked to my GitHub profile)

**Comment by sibirrer** [comment]
I close this issue as it is not directly related to the code but more to the usage. Please re-open if you want to get back to this.
