### ISSUE TITLE
Is 'UNIFORM' light profile not compatible with flux_components()?

### ISSUE THREAD

**Issue by ajshajib** [sibirrer/lenstronomy#5]
lenstronomy.Analysis.lens_analysis.flux_components() throws the following error if 'UNIFORM' light profile is provided.

> ---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-89-3520aacc5757> in <module>()
     17 
     18     lens_analysis = LensAnalysis(lens_model_output['kwargs_options'])
---> 19     deflector_flux, _ = lens_analysis.flux_components(lens_model_output['lens_light_result'])
     20     print deflector_flux
     21 

/home/ajshajib/mybin/lenstronomy/lenstronomy/Analysis/lens_analysis.pyc in flux_components(self, kwargs_light, n_grid, delta_grid, type)
    134             kwargs_copy[k]['center_y'] = 0
    135             if type == 'lens':
--> 136                 light = self.LensLightModel.surface_brightness(x_grid, y_grid, kwargs_copy, k=k)
    137             elif type == 'source':
    138                 light = self.SourceModel.surface_brightness(x_grid, y_grid, kwargs_copy, k=k)

/home/ajshajib/mybin/lenstronomy/lenstronomy/LightModel/light_model.pyc in surface_brightness(self, x, y, kwargs_lens_light_list, k)
     16         :type x: set or single 1d numpy array
     17         """
---> 18         return self.lightModel.surface_brightness(x, y, kwargs_lens_light_list, k=k)
     19 
     20 

/home/ajshajib/mybin/lenstronomy/lenstronomy/LightModel/light_model.pyc in surface_brightness(self, x, y, kwargs_list, k)
    102             if self.valid_list[i]:
    103                 if k == None or k == i:
--> 104                     flux += func.function(x, y, **kwargs_list[i])
    105         return flux
    106 

TypeError: function() got an unexpected keyword argument 'center_x'

**Comment by sibirrer** [comment]
new git push does not add 'center_x' values for models that do not require those keywords.
