### ISSUE TITLE
python2 test with zero to power of negative number

### ISSUE THREAD

**Issue by sibirrer** [sibirrer/lenstronomy#58]
@dangilman 
a python2 test fails with zero to the power of a negative number:
https://travis-ci.org/sibirrer/lenstronomy/jobs/487246114

**Comment by sibirrer** [comment]
integers as function calls give different answers in python 2 vs 3. Tests pass now, but you may want to have a look at my latest commit

**Comment by dangilman** [comment]
Yeah I’ll try to remember to pass numbers as floats from now on 

- Daniel
