### ISSUE TITLE
Light profile 'UNIFORM' not compatible with 'joint_center_lens_light': True in kwargs_constraints

### ISSUE THREAD

**Issue by ajshajib** [sibirrer/lenstronomy#7]
I think if 'joint_center_lens_light' is set to True, it inserts 'center_x' and 'center_y' keywords in the 'UNIFORM' profile parameters, which then throws the following error: 

TypeError: function() got an unexpected keyword argument 'center_x'

**Comment by sibirrer** [comment]
with latest git commit should be fixed
