### ISSUE TITLE
Spherical Gaussian density returns potential

### ISSUE THREAD

**Issue by ajshajib** [sibirrer/lenstronomy#78]
https://github.com/sibirrer/lenstronomy/blob/6727a45e4f4d9bbafdbf3622ba7e0b8faac8b0b6/lenstronomy/LensModel/Profiles/gaussian_kappa.py#L82

The functions `density()` and `density_2d()` are returning the potential calculated from Gaussian convergence. Is this expected behavior?

**Comment by sibirrer** [comment]
It's not well documented. The tests basically define in this case the usage:
    def test_density_2d(self):
        x = np.linspace(0, 5, 10)
        y = np.linspace(0, 5, 10)
        amp = 1.*2*np.pi
        center_x = 0.
        center_y = 0.
        sigma = 1.
        f_xx, f_yy, f_xy = self.gaussian_kappa.hessian(x, y, amp, sigma, center_x, center_y)
        kappa = 1./2 * (f_xx + f_yy)
        amp_3d = self.gaussian_kappa._amp2d_to_3d(amp, sigma, sigma)
        density_2d = self.gaussian_kappa.density_2d(x, y, amp_3d, sigma, center_x, center_y)
        npt.assert_almost_equal(kappa[1], density_2d[1], decimal=5)
        npt.assert_almost_equal(kappa[2], density_2d[2], decimal=5)

**Comment by ajshajib** [comment]
I see, I didn't notice that the function getting returned is from another class where the potential is Gaussian.
