### ISSUE TITLE
Issue with the ellipticity parameters during the fitting routine

### ISSUE THREAD

**Issue by ajshajib** [sibirrer/lenstronomy#8]
Below is the output of a fitting sequence. Notice that the ellipticity parameters of the lens light result are the exact same values of the ellipticity parameters of the lens result from the last fitting routine. This looks like there might be a bug that initiates the lens light result ellipticities with the last lens result ellipticities for each fitting routine.

> Computing  the PSO ...
10
20
30
40
50
60
70
80
90
100
max iteration reached! stoping
(-3.991083950193232, 'reduced X^2 of best position')
(-19171.171754753188, 'logL')
(9607, 'effective number of data points')
([{'theta_E': 2.2658532712145694, 'center_x': -0.262688967918308, 'center_y': -1.1404516783650798, **'e1': -0.6835855040117955**, 'gamma': 2.0, **'e2': 0.06766219462405391**}, {'e1': -0.17277591776609602, 'e2': -0.004212386201934322}], 'lens result')
([{'n_sersic': 1.2101341550405091, 'center_x': -0.16551583425884125, 'center_y': 0.3980786989886641, 'R_sersic': 0.01174977715669391, 'I0_sersic': 1}], 'source result')
([{'R_sersic': 0.5198435543188105, 'I0_sersic': 1, 'n_sersic': 8.54619360833984, 'center_x': -0.10394830644136022, 'center_y': 0.032031977997840855, 'e1': 0.0, 'e2': 0.0}, {'mean': 1}], 'lens light result')
([{'point_amp': 1, 'ra_image': array([-0.26293853, -1.16111134,  0.07670262,  1.25560955]), 'dec_image': array([-1.14435482,  2.00781588,  2.10684856,  1.69381513])}], 'point source result')
(251.46317219734192, 'time used for PSO', 'PSO')
===================
Computing the PSO ...
10
20
30
40
50
60
70
80
90
100
max iteration reached! stoping
(-82.09378982381793, 'reduced X^2 of best position')
(-394337.51941870945, 'logL')
(9607, 'effective number of data points')
([{'theta_E': 2.443229678717895, 'center_x': -0.31925546624338047, 'center_y': -1.3509513427731108, **'e1': -0.7557880427714526**, 'gamma': 2.0, **'e2': 0.16897409092818896**}, {'e1': -0.27709102267361096, 'e2': 0.02144742885269826}], 'lens result')
([{'n_sersic': 3.658520539312845, 'center_x': -0.11697501252269911, 'center_y': 0.2589494782305022, 'R_sersic': 0.0367272943905438, 'I0_sersic': 1}], 'source result')
([{'R_sersic': 0.7118295387881899, 'I0_sersic': 1, 'n_sersic': 10.374378125133127, 'center_x': -0.262688967918308, 'center_y': -1.1404516783650798, **'e1': -0.6835855040117955**, **'e2': 0.06766219462405391**}, {'mean': 1}], 'lens light result')
([{'point_amp': 1, 'ra_image': array([-0.32019651, -1.14376681,  0.06836124,  1.22290893]), 'dec_image': array([-1.35820856,  1.98377831,  2.08533192,  1.61804553])}], 'point source result')
(256.9203588962555, 'time used for PSO', 'PSO')
===================
iteration of step 11 gave best reconstruction.
log likelihood before: -394337.51941870945 and log likelihood after: -440520.3413147764
Computing the PSO ...
10
20
30
40
50
60
70
80
90
100
max iteration reached! stoping
(-34.42961225023929, 'reduced X^2 of best position')
(-165365.4276378993, 'logL')
(9606, 'effective number of data points')
([{'theta_E': 4.971275164006167, 'center_x': 4.674338692519211, 'center_y': 2.183729849036633, **'e1': 0.5234875406962552**, 'gamma': 1.9005320425598882, **'e2': -1.9302898068344583**}, {'e1': 0.026393279834134063, 'e2': 0.18026803969180105}], 'lens result')
([{'n_sersic': 3.918801335435724, 'center_x': 4.491783584968015, 'center_y': 2.1241156308801283, 'R_sersic': 0.03462582928108242, 'I0_sersic': 1}], 'source result')
([{'R_sersic': 0.6809958956397767, 'I0_sersic': 1, 'n_sersic': 10.62172644723493, 'center_x': -0.31925546624338047, 'center_y': -1.3509513427731108, **'e1': -0.7557880427714526**, **'e2': 0.16897409092818896**}, {'mean': 1}], 'lens light result')
([{'point_amp': 1, 'ra_image': array([-0.25592257, -1.14670748,  0.10838787,  1.19883924]), 'dec_image': array([-1.30630152,  1.97325499,  2.11690723,  1.59755353])}], 'point source result')
(297.37227487564087, 'time used for PSO', 'PSO')
===================
iteration of step 13 gave best reconstruction.
log likelihood before: -165365.4276378993 and log likelihood after: -181984.6246381529
Computing the PSO ...
10
20
30
40
50
60
70
80
90
100
max iteration reached! stoping
(-25.2987790496482, 'reduced X^2 of best position')
(-121510.0357754603, 'logL')
(9606, 'effective number of data points')
([{'theta_E': 4.971275164006167, 'center_x': 4.674338692519211, 'center_y': 2.183729849036633, **'e1': 0.5234875406962552**, 'gamma': 1.8819269229474558, **'e2': -1.9302898068344583**}, {'e1': 0.015734324898259912, 'e2': 0.18957469310475653}], 'lens result')
([{'n_sersic': 3.3324215288842756, 'center_x': 4.483217340121929, 'center_y': 2.1094410214834336, 'R_sersic': 0.09126143903235771, 'I0_sersic': 1}], 'source result')
([{'R_sersic': 0.7020202550333958, 'I0_sersic': 1, 'n_sersic': 10.263096549517757, 'center_x': 4.674338692519211, 'center_y': 2.183729849036633, **'e1': 0.5234875406962552, 'e2': -1.9302898068344583**}, {'mean': 1}], 'lens light result')
([{'point_amp': 1, 'ra_image': array([-0.28166275, -1.14653881,  0.11554444,  1.22407825]), 'dec_image': array([-1.28597166,  1.95879435,  2.11527493,  1.66086215])}], 'point source result')
(358.81216382980347, 'time used for PSO', 'PSO')
===================
iteration of step 19 gave best reconstruction.
log likelihood before: -121510.0357754603 and log likelihood after: -91156.84354035514
Computing the PSO ...
10
20
30
40
50
60
70
80
90
100
max iteration reached! stoping
(-18.86720634500439, 'reduced X^2 of best position')
(-90619.1920750561, 'logL')
(9606, 'effective number of data points')
([{'theta_E': 4.971275164006167, 'center_x': 4.674338692519211, 'center_y': 2.183729849036633, 'e1': 0.5234875406962552, 'gamma': 1.881920864557125, 'e2': -1.9302898068344583}, {'e1': 0.015731430614447414, 'e2': 0.18961217456913146}], 'lens result')
([{'n_sersic': 3.3323869710942033, 'center_x': 4.48322191155607, 'center_y': 2.109423134590232, 'R_sersic': 0.0912840088365735, 'I0_sersic': 1}], 'source result')
([{'R_sersic': 0.7022962736071097, 'I0_sersic': 1, 'n_sersic': 10.263431148119702, 'center_x': 4.674338692519211, 'center_y': 2.183729849036633, **'e1': 0.5234875406962552, 'e2': -1.9302898068344583**}, {'mean': 1}], 'lens light result')
([{'point_amp': 1, 'ra_image': array([-0.28179184, -1.14649611,  0.11546242,  1.22444828]), 'dec_image': array([-1.28623442,  1.95798722,  2.11576269,  1.66020438])}], 'point source result')
(376.12515211105347, 'time used for PSO', 'PSO')
===================
iteration of step 0 gave best reconstruction.
log likelihood before: -90619.1920750561 and log likelihood after: -95245.53921389392
1564.73388696 total time needed for computation
Result saved in: j0147_21_s_out.txt
============ CONGRATULATION, YOUR JOB WAS SUCCESSFUL ================

**Comment by ajshajib** [comment]
I just realized, it's also happenning for the center_x and center_y parameters for the lens result and light light result.

**Comment by sibirrer** [comment]
fixed with commit. Thank you!
