### ISSUE TITLE
MCMC walkers initiate outside given bounds.

### ISSUE THREAD

**Issue by ajshajib** [sibirrer/lenstronomy#9]
The MCMC walkers can be initiated outside the bounds as it seems that sigma_scale is prioritized or the bounds are not checked. Then the following issue happens as shown in the figure below. Tho horizontal axis is for MCMC steps and the 1-sigma spread of the walkers at each step are shown along the vertical axis. Two panels are for two different parameters. In the top panel, the walkers initiated outside can not come back into the allowed bounds. If the likelihood function checks for bounds and assigns -infinite log-likelihood for out-of-bounds walkers, they can't move to any other point. While initiating the walker distribution, the specified bounds need to be prioritized.

![screen shot 2018-04-30 at 11 14 15 pm](https://user-images.githubusercontent.com/20169048/39463445-debef438-4ccc-11e8-8de8-5575d65d17a3.png)

**Comment by sibirrer** [comment]
I made the change such that the mean is always in the bounds but sigma may get out of bounds in the initial cloud of MCMC points

**Comment by ajshajib** [comment]
I think, the mean_start is already ensured to be within the bounds imposed by the PSO. If there is no other potential issue of resizing the sigma_scale when it's too big, I would suggest a modification like this. This ensures the range covered by [men-sigma, mean+sigma] is within the bounds.

>low_start = mean_start - sigma_start
>high_start = mean_start + sigma_start
>low_start = np.maximum(lowerLimit, low_start)
>high_start = np.minimum(upperLimit, high_start)
>sigma_start = (high_start - low_start)/2
>mean_start = (high_start+low_start)/2
>params = np.array([mean_start, lowerLimit, upperLimit, sigma_start]).T

**Comment by sibirrer** [comment]
I updated the sigma limits. Thanks

**Comment by ajshajib** [comment]
Thanks a lot.
