### ISSUE TITLE
Change 'theta_E' keyword for Chameleon profile to reflect its actual definition

### ISSUE THREAD

**Issue by ajshajib** [sibirrer/lenstronomy#90]
Effective Einstein radius is calculated fine for SPEMD, but not for Chameleon profile.

```python
import numpy as np
import matplotlib.pyplot as plt

from lenstronomy.LensModel.lens_model import LensModel
from lenstronomy.LensModel.lens_model_extensions import LensModelExtensions


theta_es = np.linspace(0.4, 2, 30)
e1 = 0.0
e2 = 0.0

chams_theta_e = []
spemds_theta_e = []


for theta_e in theta_es:
    kwargs_chameleon = {'theta_E': theta_e, 'w_c': 1.13, 'w_t': 0.03, 'e1': e1, 'e2': e2,
                             'center_x': 0, 'center_y': 0}

    kwargs_spemd = {'theta_E': theta_e, 'gamma': 1.8, 'e1': e1, 'e2': e2, 'center_x': 0, 'center_y': 0}

    lens_model_ext_cham = LensModelExtensions(LensModel(lens_model_list=['CHAMELEON']))
    lens_model_ext_spemd = LensModelExtensions(LensModel(lens_model_list=['SPEMD']))

    spacing = 1000

    chams_theta_e.append(lens_model_ext_cham.effective_einstein_radius([kwargs_chameleon], spacing=spacing))
    spemds_theta_e.append(lens_model_ext_spemd.effective_einstein_radius([kwargs_spemd], spacing=spacing))

plt.plot(theta_es, spemds_theta_e, label='SPEMD')
plt.plot(theta_es, chams_theta_e, label='CHAMELEON')
plt.xlabel('True')
plt.ylabel('Calculated')
plt.legend()
plt.show()
```
![test](https://user-images.githubusercontent.com/20169048/59166406-23d44f00-8ade-11e9-9436-0cd47c6b8e24.png)

**Comment by ajshajib** [comment]
I see, 'theta_E' for Chameleon is not the Einstein radius, but deflection angle at 1 arcsec radius. The naming of this keyword is then very confusing, I would suggest to change it to a more appropriate one for future users.

**Comment by sibirrer** [comment]
Yes, the definition was not well documented. I changed the parameter to 'theta_1' now and added some better documentation. Thanks! I close the issue for now. Please reopen if things are not set.
With my latest push, I also changed a bit the output format of a fitting sequence and added a plotting routine that can better deal with it. Let me know if you have questions.

**Comment by ajshajib** [comment]
My subjective opinion is that `alpha_1` may be a more fitting name for the keyword, as deflection angles are conventionally expressed with alpha. The same thing can be said for the `theta_Rs` keyword in the NFW profiles (e.g., `alpha_Rs`). However, users can find the description of these keywords in the docs, so certainly this is not a major issue.

**Comment by sibirrer** [comment]
This makes sense. I just changed theta_Rs -> alpha_Rs and theta_1 -> alpha_1. It's important to have good parameter names. I can not expect that all users will go read the docs and code. Thanks, Simon

**Comment by ajshajib** [comment]
That's great! Thanks for making the changes.
