### ISSUE TITLE
test failing

### ISSUE THREAD

**Issue by sibirrer** [sibirrer/lenstronomy#92]
@aymgal the tests are failing due to multinest:
https://travis-ci.org/sibirrer/lenstronomy/jobs/547600389

you can locally do the same test when performing the tests in a virtual environment (without pre-installed multi-nest & co). One suggestion is to test only specifically the interface and move the import statements to a very narrow region in the source code that are not tested.

thanks, Simon

**Comment by ajshajib** [comment]
You can actually check if a pull request is passing the test before you accept the request. On Travis-CI, there is a tab which shows test results for pull requests.

**Comment by sibirrer** [comment]
thanks Anowar, sometimes it shows in the pull request, so I though it was passing.

**Comment by aymgal** [comment]
Or maybe I can do a "try: except:" statement around the `run(...)` method, I think it's "cleaner"

**Comment by sibirrer** [comment]
I agree. You can get inspired in how I did the 'testing' of the fastell4py routines in lenstronomy. Just make sure that the import statements are all in the except statement and do not appear outside of it.

**Comment by aymgal** [comment]
The difference with fastell4py is that it raises an error directly from the `import` statement right ?
Whereas for pymultinest, it will be imported correctly (as long as it was pip installed), then it will raise an error when `pymultinest.run` is called.

So the try/except should be around the call to `run`, but it's ok I guess

**Comment by sibirrer** [comment]
If you look in travis, it crashed before the tests started and not only when the run() call is executed, at: 
lenstronomy/Sampling/Samplers/multinest_sampler.py:10: 
    import pymultinest

**Comment by aymgal** [comment]
Ah yes because it imports directly `.run`... Ok then let's do the same than with fastell.

**Comment by aymgal** [comment]
Ok I pushed it on my branch `dev-samplers`. Should I open a new PR ?

**Comment by sibirrer** [comment]
yes please, go ahead, then you can hopefully check (see Anowar comment) whether travis passes or not

**Comment by aymgal** [comment]
@ajshajib should I do something specific when I open the PR for Travis-Cl to show up ? it does seem to be automatic, no tests are running for my last PR

**Comment by sibirrer** [comment]
the tests fail now (only) because some test take too long. It is important to have very simple fast tests. You don't have to check whether the sampler is doing what it supposed to do, only that the wrapping function is doing what it is supposed to do.

**Comment by aymgal** [comment]
> the tests fail now (only) because some test take too long. It is important to have very simple fast tests. You don't have to check whether the sampler is doing what it supposed to do, only that the wrapping function is doing what it is supposed to do.

Does the test fail for MultiNest, or the other two samplers ? Where exactly does it fails in test scripts : when `self.sampler.run`is called, or even before ?
On my computer, tests for Dynesty run in ~11 s (which is too long I guess), but DyPolyChord last ~ 3 s, and MultiNest < 0.8 s.

Also, tests are trivial when imports statement fail, which should be the case... so apparently Travis-Cl does manage to import everything in the end ? Otherwise the samplers should not run (e.g. [this code](https://github.com/aymgal/lenstronomy/blob/bc270c922aa0ed61b428e9a866b434f1858d8b15/lenstronomy/Sampling/Samplers/multinest_sampler.py#L138)

**Comment by sibirrer** [comment]
perhaps it's because the additional requirements need a long time to install and the total testing run-time is exceeded. There are options to keep the built I think, but I have not figured it out yet: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received. 11s is too long of a test (I know, some old ones are also rather long but I should also reduce them)

**Comment by aymgal** [comment]
Now that I reduced to ~ 0.8s for Dynesty, does it still fail ?
MultiNest and DyPolyChord should not be a problem since it runs trivially.

**Comment by sibirrer** [comment]
Yes, still the same problem, you can have a look at:
https://travis-ci.org/sibirrer/lenstronomy/jobs/547677516

It is the third test function in the test_fitting_sequence. Maybe you can split the test function to have a better idea of where it fails, as it is not clear for now why it is not returning anything within 10 minutes.

**Comment by sibirrer** [comment]
tests pass now, thank you!
