### ISSUE TITLE
improve tests for added samplers

### ISSUE THREAD

**Issue by sibirrer** [sibirrer/lenstronomy#94]
@aymgal: the added source code has rather low testing:
https://coveralls.io/builds/24083754
I am aware that the samplers themselves will not be testable but all the other routines should be doable. Overall test coverage of lenstronomy is reduced by 0.5%. Sorry for being peaky here, but I want to keep (and even beat) the current state of testing. Thank you!

**Comment by sibirrer** [comment]
now it's only the sampling_util. All other util functionalities are 100% tested:
https://coveralls.io/builds/24094871/source?filename=lenstronomy/Util/sampling_util.py

**Comment by aymgal** [comment]
done
